// 지시 #9c2ae902 · 멀티미디어 어댑터 공개 API 배럴.
// UI(미디어 허브) 와 서버 엔드포인트는 본 파일 하나만 import 해도 충분하도록,
// 타입·어댑터 팩토리·레지스트리를 모두 재수출한다.

export * from './types';
export { createPdfAdapter } from './PdfAdapter';
export {
  PdfAdapter,
  createRealPdfAdapter,
  parsePdf,
  generatePdf,
  PDF_ADAPTER_ID,
  type ParsedPdf,
  type PdfPage,
  type PdfImageRef,
  type PdfMetadata,
  type DocumentTree,
  type DocumentSection,
  type DocumentNode,
  type PdfParseDriver,
  type PdfGenerateDriver,
  type PdfAdapterErrorCode,
  type ParsePdfOptions,
  type GeneratePdfOptions,
  type RealPdfAdapterOptions,
} from './adapters/PdfAdapter';
export { createPptAdapter } from './PptAdapter';
export {
  PptAdapter,
  createRealPptAdapter,
  parsePpt,
  generatePpt,
  PPT_ADAPTER_ID,
  type ParsedPpt,
  type PptSlide,
  type PptImageRef as PptSlideImageRef,
  type PptShapeRef,
  type PptTableRef,
  type PptMetadata,
  type DeckTree,
  type DeckSlide,
  type DeckNode,
  type PptParseDriver,
  type PptGenerateDriver,
  type PptAdapterErrorCode,
  type ParsePptOptions,
  type GeneratePptOptions,
  type RealPptAdapterOptions,
} from './adapters/PptAdapter';
export { createVideoAdapter, VIDEO_ADAPTER_ID } from './VideoAdapter';
export { createWebSearchAdapter, WEB_SEARCH_ADAPTER_ID } from './WebSearchAdapter';
export {
  WebSearchAdapter,
  createWebSearchRealAdapter,
  registerWebSearchAdapter,
  search as webSearch,
  createBingProvider,
  createBraveProvider,
  createDuckDuckGoProvider,
  RateLimiter,
  TtlCache,
  HttpError as WebSearchHttpError,
  DEFAULT_RETRY_POLICY,
  WEB_SEARCH_REAL_ADAPTER_ID,
  WEB_SEARCH_ALIAS,
  type SearchResult,
  type SearchProvider,
  type WebSearchOptions,
  type WebSearchSettings,
  type WebSearchAdapterOptions,
  type WebSearchErrorCode,
  type RetryPolicy,
  type RateLimiterOptions,
  type TtlCacheOptions,
  type WebSearchRuntimeOptions,
  type SafeSearchLevel,
  type FreshnessFilter,
} from './adapters/WebSearchAdapter';
export { createResearchAdapter, RESEARCH_ADAPTER_ID } from './ResearchAdapter';
export {
  ResearchAdapter,
  createResearchRealAdapter,
  registerResearchAdapter,
  research as deepResearch,
  defaultDecomposer,
  defaultSummarizer,
  trustScoreForUrl,
  defaultBreadth,
  DEFAULT_BUDGET,
  RESEARCH_REAL_ADAPTER_ID,
  RESEARCH_ALIAS,
  type ResearchReport,
  type ResearchSection,
  type ResearchCitation,
  type ResearchTocItem,
  type ResearchReportMeta,
  type ResearchOptions,
  type ResearchRuntime,
  type ResearchProgress,
  type ResearchProgressHandler,
  type ResearchProgressStage,
  type ResearchDepth,
  type ResearchErrorCode,
  type ResearchBudget,
  type Decomposer,
  type DecomposedSubQuery,
  type SearchRunner,
  type SearchRunnerRequest,
  type Summarizer,
  type SummarizeRequest,
  type SummarizeResponse,
  type ResearchAdapterOptions,
} from './adapters/ResearchAdapter';
export { createInputAutomationAdapter } from './InputAutomationAdapter';
export {
  InputAutomationAdapter,
  createRealInputAutomationAdapter,
  makeInputAutomationFactory,
  matchHost,
  matchPath,
  maskSensitiveText,
  scaleEventForDpr,
  normalizeModifiers,
  INPUT_AUTOMATION_ADAPTER_ID,
  INPUT_AUTOMATION_ALIAS,
  type InputAutomationAdapterOptions,
  type InputAutomationErrorCode,
  type InputEvent,
  type InputEventKind,
  type PermissionLevel,
  type ConsentSession,
  type ConsentPort,
  type HotkeyPort,
  type InputSourcePort,
  type OsDriver,
  type ArtifactPort,
  type TimelineEvent,
  type TimelineObserver,
  type WhitelistRule,
  type AutomationTarget,
  type ReplayResult,
  type ReplayArtifacts,
  type ReplayStepOutcome,
} from './adapters/InputAutomationAdapter';
export {
  MultimediaRegistry,
  createDefaultRegistry,
  type MultimediaRegistryOptions,
} from './MultimediaRegistry';
